name: CI-CD-Pipelines-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask-application-packages1"
  EB_APPLICATION_NAME       : "myFlask"     
  EB_ENVIRONMENT_NAME       : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{giyhub.sha}}.zip"
  AWS_REGION_NAME           : "us-west-2"
  
  
  

on:
  push:
    branches:
      - master

jobs:
  my_ci_part:
    runs-on : ubuntu-latest

    steps:
    - name: Git clone our ripo
      uses: actions/checkout@v2
        
    - name: Create ZIP deployment package
      run : zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
      
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with: 
        aws-access-key-id     : ${{secrets.MY_AWS_ACCESS_KEY}}
        aws-secret-aceess-key : ${{secrets.MY_AWS_SECRET_KEY}}
        aws-region            : ${{env.AWS_REGION_NAME }}
    
    - name: Copy Deployment package to S3 bucket
      run : aws s3 cp ${{env.DEPLOY_PACKAGE_NAME}}  s3://${{ env.EB_PACKAGE_S3_;BUCKET_NAME }}/
    
    - name: Print Happy Message for CI finish
      run : echo "CI Pipeline part finished succesfully"
        
                 
     
 
